export const mockUsers = [
  {
    id: 'user_001',
    userName: 'JohnDoe',
    avatar: 'https://randomuser.me/api/portraits/men/1.jpg',
    hasStory: true,
  },
  {
    id: 'user_002',
    userName: 'JaneSmith',
    avatar: 'https://randomuser.me/api/portraits/women/2.jpg',
    hasStory: false,
  },
  {
    id: 'user_003',
    userName: 'MikeJohnson',
    avatar: 'https://randomuser.me/api/portraits/men/3.jpg',
    hasStory: true,
  },
  {
    id: 'user_004',
    userName: 'EmilyBrown',
    avatar: 'https://randomuser.me/api/portraits/women/4.jpg',
    hasStory: false,
  },
  {
    id: 'user_005',
    userName: 'ChrisWilson',
    avatar: 'https://randomuser.me/api/portraits/men/5.jpg',
    hasStory: true,
  },
  {
    id: 'user_006',
    userName: 'OliviaMartinez',
    avatar: 'https://randomuser.me/api/portraits/women/6.jpg',
    hasStory: false,
  },
  {
    id: 'user_007',
    userName: 'DanielGarcia',
    avatar: 'https://randomuser.me/api/portraits/men/7.jpg',
    hasStory: true,
  },
  {
    id: 'user_008',
    userName: 'SophiaAnderson',
    avatar: 'https://randomuser.me/api/portraits/women/8.jpg',
    hasStory: false,
  },
  {
    id: 'user_009',
    userName: 'MatthewThomas',
    avatar: 'https://randomuser.me/api/portraits/men/9.jpg',
    hasStory: true,
  },
  {
    id: 'user_010',
    userName: 'IsabellaHernandez',
    avatar: 'https://randomuser.me/api/portraits/women/10.jpg',
    hasStory: false,
  },
  {
    id: 'user_011',
    userName: 'JamesMoore',
    avatar: 'https://randomuser.me/api/portraits/men/11.jpg',
    hasStory: true,
  },
  {
    id: 'user_012',
    userName: 'MiaJackson',
    avatar: 'https://randomuser.me/api/portraits/women/12.jpg',
    hasStory: false,
  },
  {
    id: 'user_013',
    userName: 'WilliamWhite',
    avatar: 'https://randomuser.me/api/portraits/men/13.jpg',
    hasStory: true,
  },
  {
    id: 'user_014',
    userName: 'CharlotteHarris',
    avatar: 'https://randomuser.me/api/portraits/women/14.jpg',
    hasStory: false,
  },
  {
    id: 'user_015',
    userName: 'EthanClark',
    avatar: 'https://randomuser.me/api/portraits/men/15.jpg',
    hasStory: true,
  },
  {
    id: 'user_016',
    userName: 'AmeliaLewis',
    avatar: 'https://randomuser.me/api/portraits/women/16.jpg',
    hasStory: false,
  },
  {
    id: 'user_017',
    userName: 'MasonWalker',
    avatar: 'https://randomuser.me/api/portraits/men/17.jpg',
    hasStory: true,
  },
  {
    id: 'user_018',
    userName: 'HarperAllen',
    avatar: 'https://randomuser.me/api/portraits/women/18.jpg',
    hasStory: false,
  },
  {
    id: 'user_019',
    userName: 'AlexanderYoung',
    avatar: 'https://randomuser.me/api/portraits/men/19.jpg',
    hasStory: true,
  },
  {
    id: 'user_020',
    userName: 'EvelynKing',
    avatar: 'https://randomuser.me/api/portraits/women/20.jpg',
    hasStory: false,
  },
  {
    id: 'user_021',
    userName: 'BenjaminScott',
    avatar: 'https://randomuser.me/api/portraits/men/21.jpg',
    hasStory: true,
  },
  {
    id: 'user_022',
    userName: 'AbigailGreen',
    avatar: 'https://randomuser.me/api/portraits/women/22.jpg',
    hasStory: false,
  },
  {
    id: 'user_023',
    userName: 'LucasAdams',
    avatar: 'https://randomuser.me/api/portraits/men/23.jpg',
    hasStory: true,
  },
  {
    id: 'user_024',
    userName: 'EllaBaker',
    avatar: 'https://randomuser.me/api/portraits/women/24.jpg',
    hasStory: false,
  },
  {
    id: 'user_025',
    userName: 'HenryHall',
    avatar: 'https://randomuser.me/api/portraits/men/25.jpg',
    hasStory: true,
  },
];
